"""The Vision Object Model — Flow 1 + Flow 2 subset (02_VISION_OBJECT_MODEL).

The ontology is **closed**: eleven object kinds, fixed. New capability adds
instances and attributes, never new kinds.

Implemented so far:

    Flow 1   Camera · Frame · Region  (+ identity, time, space, health)
    Flow 2   Detection  (+ taxonomy, confidence, provenance, quality)

Deliberately **not** implemented, because they belong to later flows and
implementing them early would be speculative:

    Track, VisualObject (Flow 3) · Crop (Flow 4) · Attribute (Flow 5) ·
    Observation, Evidence (Flow 6) · VisionState (Flow 7)
"""

from __future__ import annotations

from .camera import (
    Camera,
    CameraStatus,
    NativeProfile,
    PipelineProfile,
    SourceSemantics,
    SourceSpec,
)
from .confidence import Confidence, ConfidenceSemantics
from .detection import (
    DETECTION_SCHEMA_VERSION,
    DecisionStep,
    Detection,
    DetectionEvidence,
    DetectionOutcome,
    ExposureLevel,
    QualityGrades,
)
from .frame import (
    DecodeQuality,
    Frame,
    FrameDimensions,
    FrameQuality,
    PixelBuffer,
    PrivacyState,
    SourceMeta,
)
from .health import (
    ComponentHealth,
    CoverageGap,
    HealthState,
    ObservabilityReason,
    ObservabilityState,
)
from .ids import (
    AdapterId,
    AttributeKey,
    BindingId,
    CalibrationId,
    CameraId,
    ClassId,
    ConfigRevision,
    DetectionId,
    FrameRef,
    FrameSeq,
    LocalTrackId,
    ModelId,
    ModuleId,
    ObjectId,
    PluginId,
    PortId,
    PrivacyPolicyId,
    ProfileId,
    RegionId,
    SiteId,
    StreamEpoch,
    TenantId,
    TrackerEpoch,
    TrackId,
    new_ulid,
    ulid_timestamp_ms,
)
from .provenance import InferenceTiming, ModelMeta, Provenance
from .region import ContainmentMethod, MembershipState, Region
from .space import (
    Box,
    Calibration,
    Ellipse,
    FrameOfReference,
    Homography,
    Point,
    Polygon,
    SpatialInfo,
)
from .taxonomy import (
    UNKNOWN_CLASS,
    ClassStatus,
    CoverageReport,
    GeometryKind,
    MappingEntry,
    TaxonomyClass,
    TaxonomyMapping,
    UnmappedPolicy,
)
from .timebase import ZERO_DURATION, ClockQuality, Duration, FrameTime, Instant
from .track import (
    TRACK_SCHEMA_VERSION,
    Association,
    AssociationMethod,
    BreakReason,
    MeasurementBasis,
    MotionEstimate,
    MotionState,
    RefusedAssociation,
    Track,
    TrackEvidence,
    TrackState,
    TrackUpdate,
)
from .visual_object import (
    OBJECT_SCHEMA_VERSION,
    Attribute,
    BindingMethod,
    ClassObservation,
    IdentityAssertion,
    LifecycleState,
    RevisionReason,
    TrackBinding,
    VisualObject,
)

__all__ = [
    "DETECTION_SCHEMA_VERSION",
    "OBJECT_SCHEMA_VERSION",
    "TRACK_SCHEMA_VERSION",
    "UNKNOWN_CLASS",
    "ZERO_DURATION",
    "AdapterId",
    "Association",
    "AssociationMethod",
    "Attribute",
    "AttributeKey",
    "BindingId",
    "BindingMethod",
    "Box",
    "BreakReason",
    "ClassObservation",
    "Calibration",
    "CalibrationId",
    "Camera",
    "CameraId",
    "CameraStatus",
    "ClassId",
    "ClassStatus",
    "ClockQuality",
    "ComponentHealth",
    "Confidence",
    "ConfidenceSemantics",
    "ConfigRevision",
    "ContainmentMethod",
    "CoverageGap",
    "CoverageReport",
    "DecisionStep",
    "DecodeQuality",
    "Detection",
    "DetectionEvidence",
    "DetectionId",
    "DetectionOutcome",
    "Duration",
    "Ellipse",
    "ExposureLevel",
    "Frame",
    "FrameDimensions",
    "FrameOfReference",
    "FrameQuality",
    "FrameRef",
    "FrameSeq",
    "FrameTime",
    "GeometryKind",
    "HealthState",
    "Homography",
    "IdentityAssertion",
    "InferenceTiming",
    "Instant",
    "LifecycleState",
    "LocalTrackId",
    "MappingEntry",
    "MeasurementBasis",
    "MembershipState",
    "ModelId",
    "ModelMeta",
    "ModuleId",
    "MotionEstimate",
    "MotionState",
    "NativeProfile",
    "ObjectId",
    "ObservabilityReason",
    "ObservabilityState",
    "PipelineProfile",
    "PixelBuffer",
    "PluginId",
    "Point",
    "Polygon",
    "PortId",
    "PrivacyPolicyId",
    "PrivacyState",
    "ProfileId",
    "Provenance",
    "QualityGrades",
    "RefusedAssociation",
    "Region",
    "RegionId",
    "RevisionReason",
    "SiteId",
    "SourceMeta",
    "SourceSemantics",
    "SourceSpec",
    "SpatialInfo",
    "StreamEpoch",
    "TaxonomyClass",
    "TaxonomyMapping",
    "TenantId",
    "Track",
    "TrackBinding",
    "TrackEvidence",
    "TrackId",
    "TrackState",
    "TrackUpdate",
    "TrackerEpoch",
    "UnmappedPolicy",
    "VisualObject",
    "new_ulid",
    "ulid_timestamp_ms",
]
