"""durable domain: cameras, evidence, incidents, frames, audit

Revision ID: 91946b102297
Revises: d1f84b293431
Create Date: 2026-08-21 15:17:57.176619
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision: str = '91946b102297'
down_revision: str | None = 'd1f84b293431'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('actor_roles', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_action_time', 'audit_events', ['action', 'occurred_at'], unique=False)
    op.create_index('ix_audit_actor_time', 'audit_events', ['actor', 'occurred_at'], unique=False)
    op.create_index('ix_audit_org_time', 'audit_events', ['organization_id', 'occurred_at'], unique=False)
    op.create_index('ix_audit_resource', 'audit_events', ['resource_type', 'resource_id'], unique=False)
    op.create_table('evidence_records',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('evidence_ref', sa.String(length=255), nullable=False),
    sa.Column('camera_key', sa.String(length=64), nullable=False),
    sa.Column('frame_ref', sa.String(length=255), nullable=False),
    sa.Column('object_id', sa.String(length=255), nullable=False),
    sa.Column('observation_id', sa.String(length=255), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('purpose', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('storage_ref', sa.String(length=512), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.String(length=64), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=255), nullable=True),
    sa.Column('deletion_reason', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'evidence_ref', name='uq_evidence_ref')
    )
    op.create_index('ix_evidence_camera_time', 'evidence_records', ['camera_key', 'captured_at'], unique=False)
    op.create_index('ix_evidence_expires', 'evidence_records', ['expires_at'], unique=False)
    op.create_index('ix_evidence_object', 'evidence_records', ['object_id'], unique=False)
    op.create_index('ix_evidence_org_state', 'evidence_records', ['organization_id', 'state'], unique=False)
    op.create_table('frame_records',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('camera_key', sa.String(length=64), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('epoch', sa.Integer(), nullable=False),
    sa.Column('frame_ref', sa.String(length=255), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('observation_count', sa.Integer(), nullable=False),
    sa.Column('source_kind', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'camera_key', 'epoch', 'sequence', name='uq_frame_identity')
    )
    op.create_index('ix_frames_camera_time', 'frame_records', ['camera_key', 'captured_at'], unique=False)
    op.create_index('ix_frames_org_time', 'frame_records', ['organization_id', 'captured_at'], unique=False)
    op.create_table('restaurants',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'slug', name='uq_restaurant_slug')
    )
    op.create_index('ix_restaurants_org', 'restaurants', ['organization_id'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('restaurant_id', sa.String(length=64), nullable=True),
    sa.Column('zone_id', sa.String(length=64), nullable=True),
    sa.Column('camera_key', sa.String(length=64), nullable=False),
    sa.Column('object_id', sa.String(length=255), nullable=False),
    sa.Column('track_id', sa.String(length=255), nullable=False),
    sa.Column('rule_id', sa.String(length=128), nullable=False),
    sa.Column('ruleset_version', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by', sa.String(length=255), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.String(length=255), nullable=True),
    sa.Column('resolution_kind', sa.String(length=32), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('finding_snapshot', sa.Text(), nullable=False),
    sa.Column('evidence_refs', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_incident_dedupe', 'incidents', ['organization_id', 'camera_key', 'object_id', 'rule_id', 'status'], unique=False)
    op.create_index('ix_incidents_camera_time', 'incidents', ['camera_key', 'created_at'], unique=False)
    op.create_index('ix_incidents_org_status', 'incidents', ['organization_id', 'status'], unique=False)
    op.create_index('ix_incidents_restaurant_time', 'incidents', ['restaurant_id', 'created_at'], unique=False)
    op.create_index('ix_incidents_status_time', 'incidents', ['status', 'created_at'], unique=False)
    op.create_table('zones',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('restaurant_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_zones_restaurant', 'zones', ['restaurant_id'], unique=False)
    op.create_table('cameras',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('restaurant_id', sa.String(length=64), nullable=False),
    sa.Column('zone_id', sa.String(length=64), nullable=True),
    sa.Column('camera_key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.String(length=255), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('rtsp_port', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Integer(), nullable=False),
    sa.Column('stream_type', sa.String(length=16), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('credential_ref', sa.String(length=512), nullable=False),
    sa.Column('analysis_fps', sa.Float(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'camera_key', name='uq_camera_key')
    )
    op.create_index('ix_cameras_org_enabled', 'cameras', ['organization_id', 'enabled'], unique=False)
    op.create_index('ix_cameras_restaurant', 'cameras', ['restaurant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cameras_restaurant', table_name='cameras')
    op.drop_index('ix_cameras_org_enabled', table_name='cameras')
    op.drop_table('cameras')
    op.drop_index('ix_zones_restaurant', table_name='zones')
    op.drop_table('zones')
    op.drop_index('ix_incidents_status_time', table_name='incidents')
    op.drop_index('ix_incidents_restaurant_time', table_name='incidents')
    op.drop_index('ix_incidents_org_status', table_name='incidents')
    op.drop_index('ix_incidents_camera_time', table_name='incidents')
    op.drop_index('ix_incident_dedupe', table_name='incidents')
    op.drop_table('incidents')
    op.drop_index('ix_restaurants_org', table_name='restaurants')
    op.drop_table('restaurants')
    op.drop_index('ix_frames_org_time', table_name='frame_records')
    op.drop_index('ix_frames_camera_time', table_name='frame_records')
    op.drop_table('frame_records')
    op.drop_index('ix_evidence_org_state', table_name='evidence_records')
    op.drop_index('ix_evidence_object', table_name='evidence_records')
    op.drop_index('ix_evidence_expires', table_name='evidence_records')
    op.drop_index('ix_evidence_camera_time', table_name='evidence_records')
    op.drop_table('evidence_records')
    op.drop_index('ix_audit_resource', table_name='audit_events')
    op.drop_index('ix_audit_org_time', table_name='audit_events')
    op.drop_index('ix_audit_actor_time', table_name='audit_events')
    op.drop_index('ix_audit_action_time', table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
